# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Azure Resources and Application
# ----------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "DurableDemo"
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest
variables:
  - group: DurableDemo

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  #   exclude:
  #     - '**/*.md'
  # paths:
  #   include:
  #     - 'Durable.Demo/*'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployQA
    displayName: Deploy to QA
    type: boolean
    default: false
  - name: runDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: string
    values:
      - None
      - Scan_Everything
    default: Scan_Everything
  - name: runPsRuleScan
    displayName: Run PSRule Bicep Scan
    type: boolean
    default: false
  - name: runGHAzDOScan
    displayName: Run GHAS Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
# This approach to optionally deploy QA works but it's not DRY
# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if eq(lower(parameters.deployQA), 'false') }}:
  - template: pipes/infra-and-function-pipe.yml
    parameters:
      variableGroupName: 'DurableDemo'
      environments: ['DEV']
      runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
      runPsRuleScan: ${{ parameters.runPsRuleScan }}
      runGHAzDOScan: ${{ parameters.runGHAzDOScan }}
      workingDirectoryCode: 'src/Durable.Demo'
      workingDirectoryInfra: '/infra/bicep'
- ${{ if eq(lower(parameters.deployQA), 'true') }}:
  - template: pipes/infra-and-function-pipe.yml
    parameters:
      variableGroupName: 'DurableDemo'
      environments: ['DEV','QA']
      runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
      runPsRuleScan: ${{ parameters.runPsRuleScan }}
      runGHAzDOScan: ${{ parameters.runGHAzDOScan }}
      workingDirectoryCode: 'src/Durable.Demo'
      workingDirectoryInfra: '/infra/bicep'
