# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Azure Resources and Application
# See readme file for info about variable group "DurableDemo"
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest
variables:
  - group: DurableDemo

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  #   exclude:
  #     - '**/*.md'
  # paths:
  #   include:
  #     - 'Durable.Demo/*'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployMultiStage
    displayName: Multi-Stage Deploy
    type: boolean
    default: false
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: false
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if eq(lower(parameters.deployMultiStage), 'false') }}:
  - template: pipes/infra-and-function-pipe.yml
    parameters:
      environments: ['DEMO']
      appFolderName: 'src/Durable.Demo'
      appSolutionName: 'Durable.Demo'
      appProjectFolderName: 'src/Durable.Demo'
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}

- ${{ if eq(lower(parameters.deployMultiStage), 'true') }}:
  - template: pipes/infra-and-function-pipe.yml
    parameters:
      environments: ['DEV','QA']
      appFolderName: 'src/Durable.Demo'
      appSolutionName: 'Durable.Demo'
      appProjectFolderName: 'src/Durable.Demo'
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}
