# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Azure Resources and Application
# ----------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "DurableDemo"
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  #   exclude:
  #     - '**/*.md'
  # paths:
  #   include:
  #     - 'Durable.Demo/*'

parameters:
  - name: deployQA
    displayName: Deploy to QA
    type: boolean
    default: false
  - name: deployProd
    displayName: Deploy to Prod
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
stages:
- variables:
  - ${{ if and(eq(lower(parameters.deployQA), 'true'), eq(lower(parameters.deployProd), 'true')) }}:
    - name: selectedEnvironments
      value: ['DEV','QA','PROD']
  - ${{ if and(eq(lower(parameters.deployQA), 'true'), eq(lower(parameters.deployProd), 'false')) }}:
    - name: selectedEnvironments
      value: ['DEV','QA']
  - ${{ if and(eq(lower(parameters.deployQA), 'false'), eq(lower(parameters.deployProd), 'true')) }}:
    - name: selectedEnvironments
      value: ['DEV','PROD']
  - ${{ if and(eq(lower(parameters.deployQA), 'false'), eq(lower(parameters.deployProd), 'false')) }}:
    - name: selectedEnvironments
      value: ['DEV']

- template: pipes/infra-and-function-pipe.yml
  parameters:
    variableGroupName: 'DurableDemo'
    environments: selectedEnvironments # ['DEV','QA','PROD']
