# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build Test Utility; compiles for both Windows (x64) and Linux; copies EXE to storage for downloading ease
# ------------------------------------------------------------------------------------------------------------------------
# Note: In order for AzFileCopy to work, you need to find the account that runs this pipeline, then add account
#   to the storage account role "Storage Blob Data Contributor"
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environmentName
  default:  'DEV'
- name: blobPrefix
  default: 'Durable-Tester/'

# ------------------------------------------------------------------------------------------------------------------------
jobs:
- deployment: DeployFiles
  displayName: 'Download Artifacts'
  environment: 'DEV'
  
- job: AzureFileCopy
  displayName: 'Copy Files to Azure Storage'

  variables:
    # Bring in environment common variable file
    - template: ../../vars/var-common.yml
    - template: ../../vars/var-source-location-console.yml
    # Bring in environment specific variable files
    - ${{ if eq(lower(parameters.environmentName), 'demo') }}:
      - template: ../../vars/var-demo.yml
    - ${{ if eq(lower(parameters.environmentName), 'dev') }}:
      - template: ../../vars/var-dev.yml
    - ${{ if eq(lower(parameters.environmentName), 'qa') }}:
      - template: ../../vars/var-qa.yml
    - ${{ if eq(lower(parameters.environmentName), 'prod') }}:
      - template: ../../vars/var-prod.yml
    - name: environmentNameLower
      value: ${{ lower(parameters.environmentName) }}
    - name: blobPrefix
      value: ${{ parameters.blobPrefix }}

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Artifacts'
    inputs:
      buildType: 'current'
      downloadType: 'single'
      downloadPath: '$(System.ArtifactsDirectory)'
      artifactName: 'drop'

  - bash: |
      storageFolderName=$(echo "downloads$(environmentNameLower)" | tr '[:upper:]' '[:lower:]')
      echo "##vso[task.setvariable variable=storageFolderName]$storageFolderName"
    displayName: 'Create Variables'
    continueOnError: true

  - task: CmdLine@2
    inputs:
      script: |
        echo "environmentNameLower=$(environmentNameLower)"
        echo "SubscriptionName=$(SubscriptionName)"
        echo "resourceGroupName=$(resourceGroupName)"
        echo "deployStorageAccountName=$(deployStorageAccountName)"
        echo "deployStorageAccountResourceGroup=$(deployStorageAccountResourceGroup)"
        echo "storageFolderName=$(storageFolderName)"
        echo "blobPrefix=$(blobPrefix)"
        echo "----------------------------------------"
        echo "##[group]Display All Environment Variables:"
        printenv | sort
        echo "##[endgroup]"
    displayName: 'Display Variables'
    continueOnError: true

  - template: list-directory-step-template.yml
    parameters:
      stepName: 'List Files'
      directoryName: $(System.DefaultWorkingDirectory)
      directoryName2: $(build.artifactstagingdirectory)

  - task: AzurePowerShell@5
    displayName: 'SA: Add Agent FW'
    inputs:
      AzureSubscription: $(SubscriptionName)
      AzurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      Inline: |
        $ip = (Invoke-WebRequest -uri "http://ifconfig.me/ip").Content
        echo "Executing: Add-AzStorageAccountNetworkRule -Name $(deployStorageAccountName) -ResourceGroupName $(deployStorageAccountResourceGroup) -IpAddressRange $ip"
        Add-AzStorageAccountNetworkRule -Name $(deployStorageAccountName) -ResourceGroupName $(deployStorageAccountResourceGroup) -IPAddressOrRange $ip
        echo "##vso[task.setvariable variable=agentIP]ip"

  - task: AzureFileCopy@6
    displayName: 'AzureFileCopy: win-x64'
    inputs:
      SourcePath: '$(System.ArtifactsDirectory)/drop/win-x64'
      azureSubscription: $(SubscriptionName)
      Destination: AzureBlob
      storage: $(deployStorageAccountName)
      ContainerName: $(storageFolderName)
      BlobPrefix: $(blobPrefix)

  - task: AzureFileCopy@6
    displayName: 'AzureFileCopy: Linux'
    inputs:
      SourcePath: '$(System.ArtifactsDirectory)/drop/Linux'
      azureSubscription: $(SubscriptionName)
      Destination: AzureBlob
      storage: $(deployStorageAccountName)
      ContainerName: $(storageFolderName)
      BlobPrefix: $(blobPrefix)

  - task: AzurePowerShell@5
    displayName: 'SA: Rmv Agent FW'
    inputs:
      AzureSubscription: $(SubscriptionName)
      AzurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      Inline: |
        $ipRange = $env:agentIP + "/32"
        echo "Executing: Remove-AzStorageAccountNetworkRule -Name $(deployStorageAccountName) -ResourceGroupName $(deployStorageAccountResourceGroup) -IpAddressRange $ipRange"
        Remove-AzStorageAccountNetworkRule -Name $(deployStorageAccountName) -ResourceGroupName $(deployStorageAccountResourceGroup) -IPAddressOrRange $ipRange
    condition: succeededOrFailed()
