# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: runMSDevSecOpsScan
  default: 'None'
- name: runGHASScan
  default: 'false'
- name: codeSection
  default: 'app'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: ScanApplication${{parameters.codeSection}}
  displayName: Scan ${{parameters.codeSection}}
  jobs:
  - template: templates/scan-code-template.yml
    parameters:
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}
      codeSection: ${{ parameters.codeSection }}
