# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Azure Resources and Function App
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: deploy.infra.and.function
on: 
  workflow_dispatch:
    inputs:
      deployToDemo:
        required: false
        default: 'true'
        type: choice
        options:
          - true
          - false
      deployToDev:
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      deployToQA:
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      deployToProd:
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      securityScan:
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

jobs:
# ------------------------------------------------------------------------------------------------------------------------
  build-app:
    name: Build Function App
    uses: ./.github/workflows/template-function-app-build.yml
    secrets: inherit
    with:
      envCode: 'demo'
      rootDirectory: 'src/Durable.Demo'
      securityScan: ${{ inputs.securityScan }}
      continueOnScanError: true

# ------------------------------------------------------------------------------------------------------------------------
  infra-demo:
    if: inputs.deployToDemo == 'true'
    name: Create Demo Infra
    needs: build-app
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      envCode: 'demo'
      securityScan: ${{ inputs.securityScan }}
      continueOnScanError: true

  infra-dev:
    if: inputs.deployToDev == 'true'
    name: Create Dev Infra
    needs: build-app
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      envCode: 'dev'
      securityScan: ${{ inputs.securityScan }}

  infra-qa:
    if: inputs.deployToQA == 'true'
    name: Create QA Infra
    needs: build-app
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      envCode: 'qa'
      securityScan: ${{ inputs.securityScan }}

  infra-prod:
    if: inputs.deployToProd == 'true'
    name: Create Prod Infra
    needs: build-app
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      envCode: 'prod'
      securityScan: ${{ inputs.securityScan }}
    
# ------------------------------------------------------------------------------------------------------------------------
  deploy-app-demo:
    if: inputs.deployToDemo == 'true'
    name: Deploy Demo App
    needs: infra-demo
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'demo'

  deploy-app-dev:
    if: inputs.deployToDev == 'true'
    name: Deploy Dev App
    needs: infra-dev
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'dev'

  deploy-app-qa:
    if: inputs.deployToQA == 'true'
    name: Deploy QA App
    needs: infra-qa
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'qa'

  deploy-app-prod:
    if: inputs.deployToProd == 'true'
    name: Deploy Prod App
    needs: infra-prod
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'prod'
        