# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Function App Only
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: deploy.functionapp
on:
  workflow_dispatch:
    inputs:
      deployToDemo:
        required: false
        default: 'true'
        type: choice
        options:
          - true
          - false
      deployToDev:
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      deployToQA:
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      deployToProd:
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

jobs:
# ------------------------------------------------------------------------------------------------------------------------
  build-app:
    name: Build Function App
    uses: ./.github/workflows/template-function-app-build.yml
    secrets: inherit
    with:
      envCode: 'demo'
      rootDirectory: 'src/Durable.Demo'

# ------------------------------------------------------------------------------------------------------------------------
  deploy-app-demo:
    if: inputs.deployToDemo == 'true'
    name: Deploy Demo App
    needs: build-app
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'demo'

  deploy-app-dev:
    if: inputs.deployToDev == 'true'
    name: Deploy Dev App
    needs: build-app
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'dev'

  deploy-app-qa:
    if: inputs.deployToQA == 'true'
    name: Deploy QA App
    needs: build-app
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'qa'

  deploy-app-prod:
    if: inputs.deployToProd == 'true'
    name: Deploy Prod App
    needs: build-app
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: 'prod'
