# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to scan files for security issues
# NOTE: If you get the error: 'Resource not accessible by integration' on the upload step
# then you will need to go into the Repository -> Settings -> Workflow Permissions
# and enable the "Read and write permissions" to be able to publish the results
# ------------------------------------------------------------------------------------------------------------------------
name: template.security.scan
run-name: Run Security Scan
on:
  workflow_call:
    inputs:
      continueOnScanError:
        required: false
        default: true
        type: boolean
      scanToRun:
        required: false
        default: 'ScanEverything'
        type: string
      workingDirectoryCode:
        required: false
        default: '/src/myProject'
        type: string
      workingDirectoryInfra:
        required: false
        default: '/infra/bicep'
        type: string
  
# ------------------------------------------------------------------------------------------------------------------------
jobs:
  scanner:
    name: Security Scan
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.0.x
          6.0.x

    # See https://github.com/microsoft/security-devops-action/wiki

    - name: Run Everything MS SecDevOps Scan 
      if: inputs.scanToRun == 'Scan_Everything' || inputs.scanToRun == 'All_Of_The_Above'
      continue-on-error: ${{ inputs.continueOnScanError || inputs.scanToRun == 'All_Of_The_Above' }} 
      uses: microsoft/security-devops-action@release/vNext
      #uses: microsoft/security-devops-action@preview
      id: msdo

    - name: Run Full Code Scan
      if: inputs.scanToRun == 'Scan_Code_All_Folders' || inputs.scanToRun == 'All_Of_The_Above'
      continue-on-error: ${{ inputs.continueOnScanError || inputs.scanToRun == 'All_Of_The_Above' }} 
      uses: microsoft/security-devops-action@release/vNext
      #uses: microsoft/security-devops-action@preview
      id: msdo2
      with:
        tools: antimalware,eslint,binskim

    - name: Run Full Infra Scan
      if: inputs.scanToRun == 'Scan_Infra_All_Folders' || inputs.scanToRun == 'All_Of_The_Above'
      continue-on-error: ${{ inputs.continueOnScanError || inputs.scanToRun == 'All_Of_The_Above' }} 
      uses: microsoft/security-devops-action@release/vNext
      #uses: microsoft/security-devops-action@preview
      id: msdo3
      with:
        tools: templateanalyzer,terrascan,trivy

      # this works to just scan source code directory...!
    - name: Run One Directory Code Scan
      if: inputs.scanToRun == 'Scan_Code_One_Folder' || inputs.scanToRun == 'All_Of_The_Above'
      continue-on-error: ${{ inputs.continueOnScanError || inputs.scanToRun == 'All_Of_The_Above' }} 
      uses: microsoft/security-devops-action@release/vNext
      #uses: microsoft/security-devops-action@preview
      id: msdo4
      env:
        gdn_run_workingdirectory: ${{ inputs.workingDirectoryCode }}
        run_workingdirectory: ${{ inputs.workingDirectoryCode }}
      with:
        tools: antimalware,eslint,binskim

    # this works to just scan infra code directory...!
    - name: Run One Directory Infra Scan
      if: inputs.scanToRun == 'Scan_Infra_One_Folder' || inputs.scanToRun == 'All_Of_The_Above'
      continue-on-error: ${{ inputs.continueOnScanError || inputs.scanToRun == 'All_Of_The_Above' }} 
      uses: microsoft/security-devops-action@release/vNext
      #uses: microsoft/security-devops-action@preview
      id: msdo5
      env:
        gdn_run_workingdirectory: ${{ inputs.workingDirectoryInfra }}
        run_workingdirectory: ${{ inputs.workingDirectoryInfra }}
      with:
        tools: templateanalyzer,terrascan,trivy

    # this should FAIL (but doesn't...) to find infra code and not throw any errors...!
    - name: Run Code Scan on Infra Folder
      if: inputs.scanToRun == 'Scan_Infra_Folder_For_Code' || inputs.scanToRun == 'All_Of_The_Above'
      continue-on-error: ${{ inputs.continueOnScanError || inputs.scanToRun == 'All_Of_The_Above' }} 
      uses: microsoft/security-devops-action@release/vNext
      #uses: microsoft/security-devops-action@preview
      id: msdo6
      env:
        gdn_run_workingdirectory: ${{ inputs.workingDirectoryInfra }}
        run_workingdirectory: ${{ inputs.workingDirectoryInfra }}
      with:
        tools: antimalware,eslint,binskim

    # this should FAIL (but doesn't...) to find infra code and not throw any errors...!
    - name: Run Infra Scan on Code Folder
      if: inputs.scanToRun == 'Scan_Code_Folder_For_Infra' || inputs.scanToRun == 'All_Of_The_Above'
      continue-on-error: ${{ inputs.continueOnScanError || inputs.scanToRun == 'All_Of_The_Above' }} 
      uses: microsoft/security-devops-action@release/vNext
      #uses: microsoft/security-devops-action@preview
      id: msdo7
      env:
        gdn_run_workingdirectory: ${{ inputs.workingDirectoryCode }}
        run_workingdirectory: ${{ inputs.workingDirectoryCode }}
      with:
        tools: templateanalyzer,terrascan,trivy

# ------------------------------------------------------------------------------------------------------------------------
    - name: Upload MS SecDevOps alerts to Security tab
      if: inputs.scanToRun == 'Scan_Everything'
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
    - name: Upload MS SecDevOps alerts to Workflow Artifacts
      if: inputs.scanToRun == 'Scan_Everything'
      uses: actions/upload-artifact@v3
      with:  
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}
# ------------------------------------------------------------------------------------------------------------------------
    - name: Upload MS SecDevOps alerts to Security tab
      if: inputs.scanToRun == 'Scan_Code_All_Folders'
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo2.outputs.sarifFile }}
    - name: Upload MS SecDevOps alerts to Workflow Artifacts
      if: inputs.scanToRun == 'Scan_Code_All_Folders'
      uses: actions/upload-artifact@v3
      with:  
        name: alerts
        path: ${{ steps.msdo2.outputs.sarifFile }}
# ------------------------------------------------------------------------------------------------------------------------
    - name: Upload MS SecDevOps alerts to Security tab
      if: inputs.scanToRun == 'Scan_Infra_All_Folders'
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo3.outputs.sarifFile }}
    - name: Upload MS SecDevOps alerts to Workflow Artifacts
      if: inputs.scanToRun == 'Scan_Infra_All_Folders'
      uses: actions/upload-artifact@v3
      with:  
        name: alerts
        path: ${{ steps.msdo3.outputs.sarifFile }}
# ------------------------------------------------------------------------------------------------------------------------
    - name: Upload MS SecDevOps alerts to Security tab
      if: inputs.scanToRun == 'Scan_Code_One_Folder'
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo4.outputs.sarifFile }}
    - name: Upload MS SecDevOps alerts to Workflow Artifacts
      if: inputs.scanToRun == 'Scan_Code_One_Folder'
      uses: actions/upload-artifact@v3
      with:  
        name: alerts
        path: ${{ steps.msdo4.outputs.sarifFile }}
# ------------------------------------------------------------------------------------------------------------------------
    - name: Upload MS SecDevOps alerts to Security tab
      if: inputs.scanToRun == 'Scan_Infra_One_Folder'
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo5.outputs.sarifFile }}
    - name: Upload MS SecDevOps alerts to Workflow Artifacts
      if: inputs.scanToRun == 'Scan_Infra_One_Folder'
      uses: actions/upload-artifact@v3
      with:  
        name: alerts
        path: ${{ steps.msdo5.outputs.sarifFile }}
# ------------------------------------------------------------------------------------------------------------------------
    - name: Upload MS SecDevOps alerts to Security tab
      if: inputs.scanToRun == 'Scan_Infra_Folder_For_Code'
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo6.outputs.sarifFile }}
    - name: Upload MS SecDevOps alerts to Workflow Artifacts
      if: inputs.scanToRun == 'Scan_Infra_Folder_For_Code'
      uses: actions/upload-artifact@v3
      with:  
        name: alerts
        path: ${{ steps.msdo6.outputs.sarifFile }}
# ------------------------------------------------------------------------------------------------------------------------
    - name: Upload MS SecDevOps alerts to Security tab
      if: inputs.scanToRun == 'Scan_Code_Folder_For_Infra'
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo7.outputs.sarifFile }}
    - name: Upload MS SecDevOps alerts to Workflow Artifacts
      if: inputs.scanToRun == 'Scan_Code_Folder_For_Infra'
      uses: actions/upload-artifact@v3
      with:  
        name: alerts
        path: ${{ steps.msdo7.outputs.sarifFile }}
                                          